### ISSUE TITLE
igscript脚本报错

### ISSUE THREAD

**Issue by Cecropis** [zhanghai/igtools#1]
使用igscript.main.kts尝试提取天之少女、壳之少女、flower春的.s文件时都会报unknown instruction code。不知道是不是环境问题，我这里的是kotlin 1.7.21。
![2023-02-04 040912](https://user-images.githubusercontent.com/30413607/216664487-d2ebdf9f-0c44-4bac-867c-beaaeb56308e.png)

**Comment by zhanghai** [comment]
这个脚本目前只支持 Flowers 系列，天之少女和壳之少女有大量推理相关的指令我并没有实现。

你可以自己在本地修改脚本，添加一下对这些 instruction code 的简单识别，这样至少大部分其他指令就能被解析了。

**Comment by Cecropis** [comment]
> 这个脚本目前只支持 Flowers 系列，天之少女和壳之少女有大量推理相关的指令我并没有实现。
> 
> 你可以自己在本地修改脚本，添加一下对这些 instruction code 的简单识别，这样至少大部分其他指令就能被解析了。

哦哦，好的，我先试一试~

**Comment by Cecropis** [comment]
> 这个脚本目前只支持 Flowers 系列，天之少女和壳之少女有大量推理相关的指令我并没有实现。
> 
> 你可以自己在本地修改脚本，添加一下对这些 instruction code 的简单识别，这样至少大部分其他指令就能被解析了。

目前看了一下一个推理部分的指令，开头的0x60 54后面接的是若干个4字节整数，每个整数各分段开头的地址；0x5F 08后接的2个字节分别表示分段号和小节号，后面2个字节是一个2字节整数指向该小节的起始地址；0x61 04后面接的2个字节也是分段号和小节号，应该是设定分段的下一次访问显示的小节。在这里每个分段对应一个可调查位置，每个可调查位置根据点击次数不同显示不同小节的对话。

**Comment by Cecropis** [comment]
> 这个脚本目前只支持 Flowers 系列，天之少女和壳之少女有大量推理相关的指令我并没有实现。
> 
> 你可以自己在本地修改脚本，添加一下对这些 instruction code 的简单识别，这样至少大部分其他指令就能被解析了。

然后有个新的指令0x82 04是加载了一张背景

**Comment by zhanghai** [comment]
如果只是想解析已经支持的指令，你也可以直接给每个未知的指令加一个 `unknownInstructionDescriptor` 就好了。

（以及指令的第二个字节是指令的参数列表长度，以及编码可能要记得改一下，日语版是 `WINDOWS_31J` 而汉化版是 `GBK`，你可能已经知道了，但姑且记录在这里.）

**Comment by shimamura-sakura** [comment]
似乎在天之少女和Flowers系列之间，一些指令的长度并不相同。如BF, 在Flowers中为BF 10, 在天之少女中为BF 04.

**Comment by FinBird** [comment]
> 似乎在天之少女和Flowers系列之间，一些指令的长度并不相同。如BF, 在Flowers中为BF 10, 在天之少女中为BF 04.

See https://github.com/Inori/FuckGalEngine/issues/59
