### ISSUE TITLE
[Question] Support for Kara no Shoujo: The Last Episode

### ISSUE THREAD

**Issue by imouto1994** [zhanghai/igtools#2]
Hi @zhanghai, thanks for your work! I just found out about your tools and want to check with you if your `igscript` manages to extract fully all the text from all`.s` files of the last Kara no Shoujo game (天ノ少女).

I have tried out the script from https://github.com/lennylxx/IG_tools but some `.s` files just returned empty text. Is it because there's no Japanese text in those `.s` files?

**Comment by zhanghai** [comment]
The igscript in this repository is only known to work with the Flowers series. I don't have a good guess from the information you provided here.
