### ISSUE TITLE
关于Flowers -Le volume sur hiver-解包

### ISSUE THREAD

**Issue by FinBird** [zhanghai/igtools#3]
感谢作者的这个项目。
不过本人在使用时遇到了一些问题，作者可否提供帮助？多谢
1.igatool解包Steam上汉化后那个版本的.iga文件，生成文件名仍为乱码：
```cmd
>igatool.exe -x data00.iga .\data00
Warning: Unknown encrypted name: 046c0517j1n6
Warning: Unknown encrypted name: 04e111jgl131
Warning: Unknown encrypted name: 05142d5f75i1
... #  省略以下150行
046c0517j1n6
04e111jgl131
05142d5f75i1
... #  省略以下150行
```
2.igascript解码上一步生成的文件，理所应当的也是乱码：
```cmd
>kotlinc -script igscript.main.kts .\data00 .\d00
.\data00\046c0517j1n6.s -> .\d00\046c0517j1n6.igs
java.lang.IllegalArgumentException: Unknown instruction code (129)
        at Igscript_main.parseInstruction(igscript.main.kts:501)
        at Igscript_main.<init>(igscript.main.kts:593)
```
汉化后的程序和iga文件如下：
[Flowers-Winters](https://disk.yandex.ru/d/k7QUIhIwvPFjbg)

**Comment by zhanghai** [comment]
第一个名字就在 https://github.com/zhanghai/igtools/blob/987dec88369df112623c5f7a21707187433c289d/igatool/encrypted_names.cpp#L320 。可能是你编译时的问题，或者 Windows 上的问题？

**Comment by FinBird** [comment]
> 第一个名字就在 https://github.com/zhanghai/igtools/blob/987dec88369df112623c5f7a21707187433c289d/igatool/encrypted_names.cpp#L320 。可能是你编译时的问题，或者 Windows 上的问题？

感谢回复！
那应该是VS编译的问题了，我是用cmake生成的sln。因为直接编译会出错，我删掉了-wall和-werror选项。
不麻烦的话？您能否提供一个Windows上的编译方案或生成文件？

**Comment by zhanghai** [comment]
不好意思，我目前完全没有 Windows 下的开发环境。不过你可以通过开个 Linux（例如 Ubuntu）虚拟机的方式来在 Linux 下编译运行。如果你在 Linux 下编译运行也遇到了问题我可以帮助。

**Comment by FinBird** [comment]
好的，我自己编译成功了，我把`unordered_map<string, string> CreateEncryptedNames()`复制到igatool.cpp就可以了（之前误删了）。
另外将
[https://github.com/zhanghai/igtools/blob/987dec88369df112623c5f7a21707187433c289d/igscript/igscript.main.kts#L572](https://github.com/zhanghai/igtools/blob/987dec88369df112623c5f7a21707187433c289d/igscript/igscript.main.kts#L572)
改成`GBK`后，输出的中文标点不正确且右侧有`\x00`,需要`str.rstrip(`)
![A%P_VI@MPP6H`Q1CU7 Z6%5](https://user-images.githubusercontent.com/35625223/232397235-464c617b-4111-46bf-a5a6-2b426703d7ef.png)
需要特殊处理，比如：
```
0x82 0xA3 ->'。'
0x82 0xA1 ->'，'
0x82 0xA5 ->'、'
```
似乎还有其他符号。不懂kotlin，作者能fix一下就好了。
